In [12]:
import numpy as np

In [3]:
A = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = A.mean(axis = 0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = A - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [15]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
print(a_centered_sp)
a_centered_sp / (5 - 1)

8.0


2.0

In [16]:
a_cov = np.cov(A.T)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [17]:
a_cov[0, 1]

2.0